//
//  EditTaskCategoryModels.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/20/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct EditTaskCategoryRequest
{
}

struct EditTaskCategoryResponse
{
    var categories = [TaskCategory]()
}

struct EditTaskCategoryViewModel
{
    var viewDataSource: [Dictionary<String, AnyObject>]
}
