//
//  EditTaskConfigurator.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/18/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class EditTaskConfigurator
{
    class var sharedInstance: EditTaskConfigurator {
        struct SingletonWrapper {
            static let sharedInstance = EditTaskConfigurator()
        }
        return SingletonWrapper.sharedInstance;
    }
    
    func configure(viewController: EditTaskViewController)
    {
        let router = EditTaskRouter()
        router.viewController = viewController
        
        let interactor = EditTaskInteractor()
        interactor.output = viewController
        
        viewController.input = interactor
        viewController.router = router
    }
}
