//
//  EditTaskInteractor.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/18/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol EditTaskInteractorInput
{
  func sendRequestData()
}

protocol EditTaskInteractorOutput
{
    func didReceiveData()
    var task: Task? {get set}
}

class EditTaskInteractor: EditTaskInteractorInput
{
    var output: EditTaskInteractorOutput!
    var worker: EditTaskWorker!
    var taskID: AnyObject!
    
    func sendRequestData()
    {
        let task: Task = SODataBaseFactory.sharedInstance.dataBase.taskForObjectID(self.taskID)!
        output.task = task
        output.didReceiveData()
    }
}
