//
//  ListTasksRouter.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/17/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListTasksRouterInput
{
  func navigateToSomewhere()
}

class ListTasksRouter: ListTasksRouterInput
{
  weak var viewController: ListTasksViewController!
  
  // MARK: Navigation
  
  func navigateToSomewhere()
  {
    // NOTE: Teach the router how to navigate to another scene. Some examples follow:
    
    // 1. Trigger a storyboard segue
    // viewController.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)
    
    // 2. Present another view controller programmatically
    // viewController.presentViewController(someWhereViewController, animated: true, completion: nil)
    
    // 3. Ask the navigation controller to push another view controller onto the stack
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
    
    // 4. Present a view controller from a different storyboard
    // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
    // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
  }
  
  // MARK: Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    if segue.identifier == "EditTaskViewController" {
      passDataToEditTaskScene(segue)
    }
  }
  
  func passDataToEditTaskScene(segue: UIStoryboardSegue)
  {
    if let selectedIndexPath = viewController.tableView.indexPathForSelectedRow {
        let selectedTask = viewController.tasks[selectedIndexPath.row]
        let editTaskViewController = segue.destinationViewController as! EditTaskViewController
        editTaskViewController.output.taskID = selectedTask.objectID!
    }
  }
}
