//
//  ListTasksConfigurator.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/17/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ListTasksPresenter: ListTasksInteractorOutput
{
}

class ListTasksConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: ListTasksConfigurator
  {
    struct Static {
      static var instance: ListTasksConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = ListTasksConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: ListTasksViewController)
  {
    let router = ListTasksRouter()
    router.viewController = viewController
    
    let presenter = ListTasksPresenter()
    presenter.output = viewController
    
    let interactor = ListTasksInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
