//
//  MainPresenter.swift
//  SwiftOrganizer
//
//  Created by Sergey Krotkih on 6/17/16.
//  Copyright (c) 2016 Sergey Krotkih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainPresenterInput
{
    func presentTasks(tasks: [Task])
}

protocol MainPresenterOutput: class
{
    func displayTasks(tasks: [Task])
}

class MainPresenter: MainPresenterInput
{
    weak var output: MainPresenterOutput!
    
    func presentTasks(tasks: [Task]){
        output.displayTasks(tasks)
    }
}
